<?php
if (!defined('ABSPATH')) exit;
if(is_user_logged_in()){wp_safe_redirect(home_url('/account/'));exit;}
get_header();
$error=isset($_GET['login_error'])?sanitize_key($_GET['login_error']):'';
$messages=array('empty'=>'لطفاً شماره موبایل یا ایمیل و رمز عبور را وارد کنید.','invalid'=>'اطلاعات ورود صحیح نیست. دوباره تلاش کنید.');
?>
<main class="melkino-auth-page"><div class="melkino-auth-shell"><section class="melkino-auth-visual"><div class="auth-visual-content"><span class="auth-visual-badge">پلتفرم هوشمند املاک رامسر</span><h2>خانه مناسب،<br>با یک حساب کاربری.</h2><p>آگهی‌های مورد علاقه‌تان را دنبال کنید، ملک ثبت کنید و وضعیت آگهی‌های خود را از یک پنل مدیریت کنید.</p><div class="auth-points"><span>مدیریت آگهی‌ها</span><span>پیگیری درخواست‌ها</span><span>ثبت ملک سریع</span></div></div></section><section class="melkino-auth-form"><div class="auth-top"><div class="auth-brand"><strong>ملکینو</strong><span>پلتفرم هوشمند املاک رامسر</span></div><a class="auth-back" href="<?php echo esc_url(home_url('/')); ?>">← بازگشت به خانه</a></div><div class="auth-title"><span class="kicker">خوش آمدید</span><h1>ورود به حساب کاربری</h1><p>برای ادامه وارد حساب ملکینو شوید.</p></div><?php if($error&&isset($messages[$error])): ?><div class="auth-alert error"><?php echo esc_html($messages[$error]); ?></div><?php endif; ?><form class="auth-form" method="post"><input type="hidden" name="melkino_login_form" value="1"><?php wp_nonce_field('melkino_login_submit','melkino_login_nonce'); ?><div class="auth-field"><label for="login_identifier">شماره موبایل یا ایمیل</label><input id="login_identifier" name="login_identifier" type="text" autocomplete="username" placeholder="شماره موبایل یا ایمیل خود را وارد کنید" required></div><div class="auth-field"><label for="login_password">رمز عبور</label><input id="login_password" name="login_password" type="password" autocomplete="current-password" placeholder="رمز عبور خود را وارد کنید" required></div><div class="auth-row"><label class="auth-check"><input type="checkbox" name="login_remember" value="1"> مرا به خاطر بسپار</label><a class="auth-link" href="<?php echo esc_url(wp_lostpassword_url(home_url('/login/'))); ?>">رمز عبور را فراموش کرده‌اید؟</a></div><button class="auth-submit" type="submit">ورود به حساب</button><div class="auth-divider"><span>یا</span></div><p class="auth-switch">حساب کاربری ندارید؟ <a href="<?php echo esc_url(home_url('/register/')); ?>">ثبت نام کنید</a></p></form><div class="auth-security">🔒 اطلاعات شما محرمانه و امن نگهداری می‌شود.</div></section></div></main>
<?php get_footer(); ?>
