<?php
if (!defined('ABSPATH')) exit;
if(is_user_logged_in()){wp_safe_redirect(home_url('/account/'));exit;}
get_header();
$error=isset($_GET['register_error'])?sanitize_key($_GET['register_error']):'';
$messages=array('required'=>'لطفاً همه اطلاعات ضروری را تکمیل و قوانین را تأیید کنید.','weak'=>'رمز عبور باید حداقل ۸ کاراکتر باشد.','match'=>'رمز عبور و تکرار آن یکسان نیست.','mobile'=>'این شماره موبایل قبلاً ثبت شده است.','email'=>'این ایمیل قبلاً ثبت شده است.','general'=>'ثبت نام انجام نشد. دوباره تلاش کنید.');
?>
<main class="melkino-auth-page"><div class="melkino-auth-shell"><section class="melkino-auth-visual"><div class="auth-visual-content"><span class="auth-visual-badge">عضویت در ملکینو</span><h2>حساب خودت را<br>بساز و شروع کن.</h2><p>با ثبت نام در ملکینو، مدیریت آگهی‌ها و پیگیری وضعیت ملک‌های ثبت‌شده ساده‌تر می‌شود.</p><div class="auth-points"><span>پنل شخصی</span><span>مدیریت آگهی</span><span>پیگیری وضعیت</span></div></div></section><section class="melkino-auth-form"><div class="auth-top"><div class="auth-brand"><strong>ملکینو</strong><span>پلتفرم هوشمند املاک رامسر</span></div><a class="auth-back" href="<?php echo esc_url(home_url('/')); ?>">← بازگشت به خانه</a></div><div class="auth-title"><span class="kicker">شروع کنید</span><h1>ثبت نام در ملکینو</h1><p>یک حساب کاربری بسازید و تجربه بهتری داشته باشید.</p></div><?php if($error&&isset($messages[$error])): ?><div class="auth-alert error"><?php echo esc_html($messages[$error]); ?></div><?php endif; ?><form class="auth-form" method="post"><input type="hidden" name="melkino_register_form" value="1"><?php wp_nonce_field('melkino_register_submit','melkino_register_nonce'); ?><div class="auth-field"><label for="register_name">نام و نام خانوادگی</label><input id="register_name" name="register_name" type="text" autocomplete="name" placeholder="نام و نام خانوادگی خود را وارد کنید" required></div><div class="auth-field"><label for="register_mobile">شماره موبایل</label><input id="register_mobile" name="register_mobile" type="tel" autocomplete="tel" placeholder="شماره موبایل خود را وارد کنید" required></div><div class="auth-field"><label for="register_email">ایمیل <small>(اختیاری)</small></label><input id="register_email" name="register_email" type="email" autocomplete="email" placeholder="ایمیل خود را وارد کنید"></div><div class="auth-field"><label for="register_password">رمز عبور</label><input id="register_password" name="register_password" type="password" autocomplete="new-password" placeholder="حداقل ۸ کاراکتر" minlength="8" required></div><div class="auth-field"><label for="register_password_confirm">تکرار رمز عبور</label><input id="register_password_confirm" name="register_password_confirm" type="password" autocomplete="new-password" placeholder="رمز عبور را دوباره وارد کنید" minlength="8" required></div><label class="auth-check"><input type="checkbox" name="register_agree" value="1" required> قوانین و شرایط استفاده را مطالعه کرده‌ام و می‌پذیرم.</label><button class="auth-submit" type="submit">ثبت نام</button><div class="auth-divider"><span>یا</span></div><p class="auth-switch">قبلاً حساب کاربری دارید؟ <a href="<?php echo esc_url(home_url('/login/')); ?>">وارد شوید</a></p></form><div class="auth-security">🔒 اطلاعات شما محرمانه و امن نگهداری می‌شود.</div></section></div></main>
<?php get_footer(); ?>
